# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNum', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=10)),
                ('hostel', models.CharField(max_length=100)),
                ('roomNum', models.IntegerField()),
                ('contactNum', models.CharField(max_length=15)),
            ],
        ),
    ]
